
CXX = g++
CFLAGS = -Wall -Werror


INCLUDE = -I/usr/local/include
LDFLAGS = -l/usr/local/lib
LDLIBS = -lcurl -ltidy -lxerces-c -lxalan-c

SOURCES_SIMPLETEST = src/shared/vars.cpp src/shared/args.cpp src/model/form_data.cpp src/curl-helper/curl_helper.cpp src/curl-helper/curl_session.cpp src/curl-helper/init_curl.cpp src/log/log.cpp src/test/simpletest.cpp

SIMPLE_OUT = simpletest.out

simpletest: simpletest_build

simpletest_build: $(SOURCES_SIMPLETEST)
	$(CXX) -o $(SIMPLE_OUT) $(INCLUDE) $(LDLIBS) $(CFLAGS) $(SOURCES_SIMPLETEST) 

SOURCES_POSTTEST = src/shared/vars.cpp src/shared/args.cpp src/model/form_data.cpp src/curl-helper/curl_helper.cpp src/curl-helper/curl_session.cpp src/curl-helper/init_curl.cpp src/log/log.cpp src/test/posttest.cpp

POST_OUT = posttest.out

posttest: posttest_build

posttest_build: $(SOURCES_POSTTEST)
	$(CXX) -o $(POST_OUT) $(INCLUDE) $(LDLIBS) $(CFLAGS) $(SOURCES_POSTTEST)




# TIDY TEST
SOURCES_TIDY = src/shared/vars.cpp src/log/log.cpp src/test/tidy_test.cpp src/tidy-helper/tidy_converter.cpp

TIDY_OUT = tidytest.out

tidytest: tidytest_build

tidytest_build: $(SOURCES_TIDY)
	$(CXX) -std=c++11 -o $(TIDY_OUT) $(INCLUDE) $(LDLIBS) $(CFLAGS) $(SOURCES_TIDY)




# XML TEST
SOURCES_XML = src/xml-helper/xml_node.cpp src/xml-helper/xml_document.cpp src/test/xml_test.cpp src/shared/vars.cpp src/log/log.cpp

XML_OUT = xmltest.out

xmltest: xmltest_build

xmltest_build: $(SOURCES_XML)
	$(CXX) -std=c++11 -g3 -ggdb3 -O0 -o $(XML_OUT) $(INCLUDE) $(LDLIBS) $(CFLAGS) $(SOURCES_XML)



